name: CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy_gh_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Compile Sass to CSS
        run: |
          npm install
          npm run build
          rm -rf node_modules
      - name: Upload to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
